name: Hello World on Linux

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: |
          echo "Hello World from Linux Runner!"
